name: 復刊ドットコムの復刊投票コメントを取得する

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: yarn
    - name: $ yarn install
      run: |
        yarn install --frozen-lockfile
    - name: ESLint
      run: |
        npx eslint
    - name: ビルドする
      run: |
        yarn build
    - name: CLI の挙動を確認する
      run: |
        ./fukkan_comments.js --version
        ./fukkan_comments.js --help
    - name: CLI を実行する
      run: |
        npx playwright install --with-deps
        ./fukkan_comments.js -b 65317 -p 2 -o output/fukkan_comments_by_github_actions.csv
    - name: 生成された CSV ファイルなどをアーカイブする
      uses: actions/upload-artifact@v4
      with:
        name: created-csv-file
        path: |
          output
